### PR TITLE
Created Landing Page

### PR DESCRIPTION
**Pull request by devanshiv123**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/HakinCodes/Malaria-Detection/blob/master/CONTRIBUTING.md)?

Yes
### Description

Created landing page 

### Checklist

- [x] I've read the contribution guidelines.
- [x] This PR mets all the requirements like Clean Code, proper README and Documentation

### Related Issues or Pull Requests

Fixes: #[123] 

### Screenshots (if any)

 Original           | Updated
image

image
image

### CODE REVIEW

**Review by sarthakkundra — CHANGES_REQUESTED** [review]
@devanshiv123 what is the [-------------url..... on the screenshot?
Also the page does not seem to be responsive, please do that too.

**Comment by devanshiv123** [comment]
> @devanshiv123 what is the [-------------url..... on the screenshot?
> Also the page does not seem to be responsive, please do that too.

I think the url thing was in the PR template only. I have edited it. I will make it responsive.

**Comment by HarshCasper** [comment]
Are you working on it @devanshiv123 ?

**Comment by devanshiv123** [comment]
> Are you working on it @devanshiv123 ?

@HarshCasper I have been working on it but I am not able to make it fully responsive. Please assign the issue to someone else if you want to, I dont think I will be able to do it in time. I am really sorry.

**Pull request closed without merging**
