### PR TITLE
Added cnn model using pytorch #127

### PR DESCRIPTION
**Pull request by kritikaparmar-programmer**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/HakinCodes/Malaria-Detection/blob/master/CONTRIBUTING.md)?

Yes

### Description

Added CNN model using Pytorch

### Checklist

- [x] I've read the contribution guidelines.
- [x] This PR mets all the requirements like Clean Code, proper README and Documentation

### Related Issues or Pull Requests

Fixes: #[Issue number that will be closed through this PR] 
#127

### CODE REVIEW

**Comment by HarshCasper** [comment]
@kritikaparmar-programmer Please use meaningful File Names for the purpose. Also, you have not documented any part of your code. Kindly do that, before I merge it.

**Comment by kritikaparmar-programmer** [comment]
Hey @HarshCasper , take a look now

**Review by macabdul9 — APPROVED** [review]
Appreciate your contribution, although I was expecting more like tensorboard logs and more metrics. Merging this, you can create separate PR if you come up with some improvement to this notebook.

**Comment by kritikaparmar-programmer** [comment]
> Appreciate your contribution, although I was expecting more like tensorboard logs and more metrics. Merging this, you can create separate PR if you come up with some improvement to this notebook.

Okayy !!

**Pull request merged**
