### PR TITLE
LandingUI With assets and preview

### PR DESCRIPTION
**Pull request by ashishsahu1**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/HakinCodes/Malaria-Detection/blob/master/CONTRIBUTING.md)?

Yes

### Description

I have attached the complete landing page design which includes different assets which will help web developer while making the same.

### Checklist

- [x] I've read the contribution guidelines.
- [x] This PR mets all the requirements like Clean Code, proper README and Documentation

### Related Issues or Pull Requests

#6 

### Screenshots (if any)

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot** | **updated screenshot**|
WebUILight
WebUIDark

### CODE REVIEW

**Comment by BALaka-18** [comment]
@ashishsahu1 what is that 'XXXXXXXXXXXXXXXXXXXXXXX' in the bottom right corner ?

**Comment by ashishsahu1** [comment]
> @ashishsahu1 what is that 'XXXXXXXXXXXXXXXXXXXXXXX' in the bottom right corner ?

That's just a text area to write the footer part, something like copyright, and few more.

**Comment by BALaka-18** [comment]
> > @ashishsahu1 what is that 'XXXXXXXXXXXXXXXXXXXXXXX' in the bottom right corner ?
> 
> That's just a text area to write the footer part, something like copyright, and few more.

Okay got it.

**Comment by sarthakkundra** [comment]
@ashishsahu1 How are you proposing to shift between dark and light mode? I don't see any toggle switch or something?

**Comment by BALaka-18** [comment]
> @ashishsahu1 How are you proposing to shift between dark and light mode? I don't see any toggle switch or something?

There's a Theme option in the top right corner. I guess that is the toggle, right @ashishsahu1 ?

**Comment by ashishsahu1** [comment]
> > @ashishsahu1 How are you proposing to shift between dark and light mode? I don't see any toggle switch or something?
> 
> There's a Theme option in the top right corner. I guess that is the toggle, right @ashishsahu1 ?

**Yes** for the UX of the web page, I have provided a video to help others.

**Review by BALaka-18 — APPROVED** [review]
Approving from my end.

**Review by sarthakkundra — APPROVED** [review]

**Pull request merged**
