### PR TITLE
Home Page for React 

### PR DESCRIPTION
**Pull request by nooras**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/HakinCodes/Malaria-Detection/blob/master/CONTRIBUTING.md)?

Yes

### Description

- Home page for react app
- Images add on home page
- Button and Font (Bunch blossom Personal Use and Monsterrat) added

### Checklist

- [x] I've read the contribution guidelines.
- [x] This PR mets all the requirements like Clean Code, proper README and Documentation

### Related Issues or Pull Requests

Fixes: #106 

### Screenshots (if any)

 Original           | Updated
 :--------------------: |:--------------------:
 **Homepagenew** | **updated screenshot**|

Ignore colour quality

### CODE REVIEW

**Comment by nooras** [comment]
Checkout @sarthakkundra

**Review by sarthakkundra — CHANGES_REQUESTED** [review]
Good work @nooras just a few changes.
1) The yarn.lock file seems to be deleted, please look into that.
2) Use 'Route' from React router instead of creating functions in router.js . That'll improve the readability of the code.
3) If you're removing any line. Remove it instead of commenting it as you've done it in App.css I believe.
Please make the following changes and make a PR ASAP.

**Comment by nooras** [comment]
> Good work @nooras just a few changes.
> 
> 1. The yarn.lock file seems to be deleted, please look into that.
> 2. Use 'Route' from React router instead of creating functions in router.js . That'll improve the readability of the code.
> 3. If you're removing any line. Remove it instead of commenting it as you've done it in App.css I believe.
>    Please make the following changes and make a PR ASAP.

updated changes @sarthakkundra

**Review by sarthakkundra — CHANGES_REQUESTED** [review]
the package-lock.json file seems to be deleted now. Just run npm install in the root folder of the front-end and that should solve that issue.

**Comment by nooras** [comment]
> the package-lock.json file seems to be deleted now. Just run npm install in the root folder of the front-end and that should solve that issue.

File added package-lock @sarthakkundra sir ... do checkout :)

**Comment by sarthakkundra** [comment]
@nooras Great work! 👍

**Comment by HarshCasper** [comment]
@nooras Resolve the Conflicts ASAP before I merge it to the Branch. This is taking a lot of time.

**Comment by nooras** [comment]
> @nooras Resolve the Conflicts ASAP before I merge it to the Branch. This is taking a lot of time.

Removed Conflict @HarshCasper checkout PR...

**Comment by nooras** [comment]
Reminder @HarshCasper  & @sarthakkundra Checkout PR... Thanks

**Pull request merged**
